In [100]:
import numpy as np
import random
import gym
import gym_2048

In [101]:
def numpy_transformer(matrix):
    lst = []
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            lst.append(int(matrix[i][j]))
    return lst

In [102]:
env = gym.make("2048-v0")
env.render()

C:\Users\Lutharsanen\Anaconda3\lib\site-packages\gym_2048\env.py:120: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  board[tile_locs] = tiles


0 	0 	2 	0
0 	0 	0 	0
0 	0 	0 	0
0 	0 	0 	0


In [115]:
action_size = env.action_space.n
print("Action size ", action_size)

state_size = 16
print("State size ", state_size)

Action size  4
State size  16


In [116]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [118]:
total_episodes = 50000        # Total episodes
total_test_episodes = 100     # Total test episodes
max_steps = 1                # Max steps per episode

learning_rate = 0.7           # Learning rate
gamma = 0.618                 # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability 
decay_rate = 0.01             # Exponential decay rate for exploration prob

In [120]:
# 2 For life or until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    state_trans = numpy_transformer(state)
    
    for step in range(max_steps):
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0,1)
        
        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state_trans,:])
        
        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()
        
        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)
        
        new_state_trans = numpy_transformer(new_state)
        

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        qtable[state_trans, action] = qtable[state_trans, action] + learning_rate * (reward + gamma * np.max(qtable[new_state_trans, :]) - qtable[state_trans, action])
                
        # Our new state is state
        state_trans = new_state_trans
        
        print(step)
        print(qtable[new_state_trans])
        
        # If done : finish episode
        if done == True: 
            break
    
    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)

0
[[4.75634946 0.88738373 1.50276773 1.46282185]
 [4.75634946 0.88738373 1.50276773 1.46282185]
 [4.75634946 0.88738373 1.50276773 1.46282185]
 [4.75634946 0.88738373 1.50276773 1.46282185]
 [4.75634946 0.88738373 1.50276773 1.46282185]
 [4.75634946 0.88738373 1.50276773 1.46282185]
 [4.75634946 0.88738373 1.50276773 1.46282185]
 [4.75634946 0.88738373 1.50276773 1.46282185]
 [4.75634946 0.88738373 1.50276773 1.46282185]
 [4.75634946 0.88738373 1.50276773 1.46282185]
 [4.75634946 0.88738373 1.50276773 1.46282185]
 [4.75634946 0.88738373 1.50276773 1.46282185]
 [0.65009732 0.         1.21128    0.        ]
 [4.75634946 0.88738373 1.50276773 1.46282185]
 [4.75634946 0.88738373 1.50276773 1.46282185]
 [4.75634946 0.88738373 1.50276773 1.46282185]]
0
[[3.48450162 0.88738373 1.50276773 1.46282185]
 [3.48450162 0.88738373 1.50276773 1.46282185]
 [3.48450162 0.88738373 1.50276773 1.46282185]
 [3.48450162 0.88738373 1.50276773 1.46282185]
 [3.48450162 0.88738373 1.50276773 1.46282185]
 [3.4845

C:\Users\Lutharsanen\Anaconda3\lib\site-packages\gym_2048\env.py:120: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  board[tile_locs] = tiles


IndexError: index 5 is out of bounds for axis 1 with size 4

In [110]:
print((qtable[4]))

[16.28736043  6.97573751 11.46422091  7.32976448]


In [52]:

env.reset()
rewards = []

for episode in range(total_test_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0
    #print("****************************************************")
    #print("EPISODE ", episode)

    for step in range(max_steps):
        # UNCOMMENT IT IF YOU WANT TO SEE OUR AGENT PLAYING
        # env.render()
        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state_trans,:])
        
        new_state, reward, done, info = env.step(action)
        
        total_rewards += reward
        
        if done:
            rewards.append(total_rewards)
            #print ("Score", total_rewards)
            break
        state = new_state
env.close()
print ("Score over time: " +  str(sum(rewards)/total_test_episodes))


C:\Users\Lutharsanen\Anaconda3\lib\site-packages\gym_2048\env.py:120: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  board[tile_locs] = tiles


Score over time: 1.6
